### ISSUE TITLE
🐛  ModuleNotFoundError: No module named 'sklearn.externals.joblib' in clodsa/augmentors/folderKerasSemanticSegmentationAugmentor.py

### ISSUE THREAD

**Issue by jpainam** [joheras/CLoDSA#35]
Hi, the package `sklearn` seems to have updated their `.externals` module and remove `.joblib`. `joblib` now is an independent package. But `clodsa` still import `Parallel` from `sklearn.externals.joblib`. Kindly update `the imports`
```python
Traceback (most recent call last):
  File "data_augmentation_with_annotation.py", line 1, in <module>
    from clodsa.augmentors.augmentorFactory import createAugmentor
  File "/home/fst/anaconda3/lib/python3.7/site-packages/clodsa/__init__.py", line 2, in <module>
    from . import augment
  File "/home/fst/anaconda3/lib/python3.7/site-packages/clodsa/augment.py", line 2, in <module>
    from .augmentors.augmentorFactory import createAugmentor
  File "/home/fst/anaconda3/lib/python3.7/site-packages/clodsa/augmentors/__init__.py", line 1, in <module>
    from .augmentorFactory import *
  File "/home/fst/anaconda3/lib/python3.7/site-packages/clodsa/augmentors/augmentorFactory.py", line 2, in <module>
    from .augmentorsList import Augmentors
  File "/home/fst/anaconda3/lib/python3.7/site-packages/clodsa/augmentors/augmentorsList.py", line 3, in <module>
    from .folderKerasSemanticSegmentationAugmentor import FolderKerasSemanticSegmentationAugmentor
  File "/home/fst/anaconda3/lib/python3.7/site-packages/clodsa/augmentors/folderKerasSemanticSegmentationAugmentor.py", line 10, in <module>
    from sklearn.externals.joblib import Parallel, delayed
ModuleNotFoundError: No module named 'sklearn.externals.joblib'
```
Trying to reinstall `clodsa` gives this output
```python
pip install clodsa
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Requirement already satisfied: clodsa in /home/fst/anaconda3/lib/python3.7/site-packages (1.2.39)
Requirement already satisfied: Keras in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (2.4.3)
Requirement already satisfied: commentjson in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (0.8.3)
Requirement already satisfied: scipy in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (1.5.2)
Requirement already satisfied: mahotas in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (1.4.10)
Requirement already satisfied: numpy in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (1.17.5)
Requirement already satisfied: h5py in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (2.10.0)
Requirement already satisfied: imutils in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (0.5.3)
Requirement already satisfied: progressbar2 in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (3.51.4)
Requirement already satisfied: scikit-learn in /home/fst/anaconda3/lib/python3.7/site-packages (from clodsa) (0.23.2)
Requirement already satisfied: pyyaml in /home/fst/anaconda3/lib/python3.7/site-packages (from Keras->clodsa) (5.3.1)
Requirement already satisfied: lark-parser<0.8.0,>=0.7.1 in /home/fst/anaconda3/lib/python3.7/site-packages (from commentjson->clodsa) (0.7.8)
Requirement already satisfied: six in /home/fst/anaconda3/lib/python3.7/site-packages (from h5py->clodsa) (1.15.0)
Requirement already satisfied: python-utils>=2.3.0 in /home/fst/anaconda3/lib/python3.7/site-packages (from progressbar2->clodsa) (2.4.0)
Requirement already satisfied: joblib>=0.11 in /home/fst/anaconda3/lib/python3.7/site-packages (from scikit-learn->clodsa) (0.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/fst/anaconda3/lib/python3.7/site-packages (from scikit-learn->clodsa) (2.1.0)
```

**Comment by joheras** [comment]
This issue has been fixed with the new version of Clodsa.
```
pip install clodsa==1.2.43
```

Best,
Jónathan
