### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by sagarkalburgi** [joheras/CLoDSA#41]
I'm getting the following error:

```
Traceback (most recent call last):
  File "clodsa_1.py", line 2, in <module>
    from clodsa.augmentors.augmentorFactory import createAugmentor
  File "D:\anaconda3\envs\yolact\lib\site-packages\clodsa\__init__.py", line 2, in <module>
    from . import augment
  File "D:\anaconda3\envs\yolact\lib\site-packages\clodsa\augment.py", line 2, in <module>
    from .augmentors.augmentorFactory import createAugmentor
  File "D:\anaconda3\envs\yolact\lib\site-packages\clodsa\augmentors\__init__.py", line 1, in <module>
    from .augmentorFactory import *
  File "D:\anaconda3\envs\yolact\lib\site-packages\clodsa\augmentors\augmentorFactory.py", line 2, in <module>
    from .augmentorsList import Augmentors
  File "D:\anaconda3\envs\yolact\lib\site-packages\clodsa\augmentors\augmentorsList.py", line 3, in <module>
    from .folderKerasSemanticSegmentationAugmentor import FolderKerasSemanticSegmentationAugmentor
  File "D:\anaconda3\envs\yolact\lib\site-packages\clodsa\augmentors\folderKerasSemanticSegmentationAugmentor.py", line 10, in <module>
    from sklearn.externals.joblib import Parallel, delayed
ModuleNotFoundError: No module named 'sklearn.externals.joblib'
```

Could you help me in resolving it?

**Comment by joheras** [comment]
This issue was fixed with the latest release of Clodsa. Check that you have it:
```
pip install clodsa==1.2.43
```

Best,
Jónathan

**Comment by sagarkalburgi** [comment]
> This issue was fixed with the latest release of Clodsa. Check that you have it:
> 
> ```
> pip install clodsa==1.2.43
> ```
> 
> Best,
> Jónathan

After installing the specified version, I'm getting the following error:
```AttributeError: 'NoneType' object has no attribute 'shape```
