### ISSUE TITLE
 clodsa building_folder_folder_linear.json  _img.empty() in function 'cv::imwrite'

### ISSUE THREAD

**Issue by monkeycc** [joheras/CLoDSA#57]
```
 clodsa building_folder_folder_linear.json
Traceback (most recent call last):
  File "E:\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\anaconda3\Scripts\clodsa.exe\__main__.py", line 7, in <module>
  File "E:\anaconda3\lib\site-packages\clodsa\command_line.py", line 9, in main
    augment.main(arg1)
  File "E:\anaconda3\lib\site-packages\clodsa\augment.py", line 40, in main
    augmentor.applyAugmentation()
  File "E:\anaconda3\lib\site-packages\clodsa\augmentors\folderLinearSemanticSegmentationAugmentor.py", line 77, in applyAugmentation
    Parallel(n_jobs=-1)(delayed(readAndGenerateImageSegmentation)
  File "E:\anaconda3\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "E:\anaconda3\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "E:\anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "E:\anaconda3\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "E:\anaconda3\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:799: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
```
 clodsa building_folder_folder_linear.json

```

  "parameters":{
    "labelsExtension":".tif",
    "outputPath":"F:/augmentation-segmentation-master/docs/datasets/semantic_segmentation/OUT/"
  },
  "annotation_mode":"folders",
  "input_path":"F:/augmentation-segmentation-master/docs/datasets/semantic_segmentation/buildings"
```

**Comment by joheras** [comment]
Hi,
Could you send me an example to replicate that problem?
Best,
Jónathan
